version: '3'

services:

  # Proxy for ssl termination and easier hostname access
  # SSL certificates with the virtual host name need to be added to ./data/ssl
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/ssl/:/etc/nginx/certs
    depends_on:
      - nextcloud
    networks:
      default:
        aliases:
          - ${NEXTCLOUD_DOMAIN}
          - ${COLLABORA_DOMAIN}

  nextcloud:
    build:
      context: ./docker/
    environment:
      SQL: 'mysql'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "${NEXTCLOUD_DOMAIN:-nextcloud.local}"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data:/var/www/html/data
      - config:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      - database-mysql
      - redis
      - mail

  # Separate app server

  # nextcloud-2:
  #   build:
  #     context: ./docker/
  #   environment:
  #     SQL: 'mysql'
  #     NEXTCLOUD_AUTOINSTALL: "NO"
  #     NEXTCLOUD_AUTOINSTALL_APPS: ""
  #   volumes:
  #     - '/home/jus/repos/nextcloud/server:/var/www/html'
  #     - data:/var/www/html/data
  #     - config:/var/www/html/config
  #     - /var/www/html/apps-writable
  #   ports:
  #     - "${PORTBASE:-800}1:80"
  #   depends_on:
  #     - database-mysql
  #     - redis

  database-mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'nextcloud'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'
    ports:
      - "${PORTBASE:-800}2:80"

  redis:
    image: redis:3

  ldap:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    expose:
      - 389
      - 636
    volumes:
      - ./data/example.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  # Using https://github.com/kristophjunge/docker-test-saml-idp

  # saml:
  #   image: kristophjunge/test-saml-idp
  #   environment:
  #     SIMPLESAMLPHP_SP_ENTITY_ID: http://nextcloud/
  #     SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/test-sp
  #     SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
  #   ports:
  #     - "${PORTBASE:-800}8:8080"

  mail:
    image: mailhog/mailhog
    ports:
      - "${PORTBASE:-800}9:8025"

  # TODO: Add S3 storage
  # TODO: Add SMB server

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  collabora:
    image: collabora/code
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      domain: ${NEXTCLOUD_DOMAIN}
      username: admin
      password: admin
      VIRTUAL_HOST: ${COLLABORA_DOMAIN}
      VIRTUAL_PORT: 9980
      VIRTUAL_PROTO: https

  s3.minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: nextcloud
      MINIO_SECRET_KEY: nextcloud
    ports:
      - "${PORTBASE:-800}5:9000"
    command: server /data

volumes:
  data:
  config:


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-192.168.21.0/24}
