version: '2'

services:
  nc-blackfire:
    image: blackfire/blackfire
    volumes:
      - ./exampledata/example.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      BLACKFIRE_SERVER_ID:
      BLACKFIRE_SERVER_TOKEN:
      BLACKFIRE_CLIENT_ID:
      BLACKFIRE_CLIENT_TOKEN:
      BLACKFIRE_LOG_LEVEL: '4'
