version: '2'

services:
  nc-server-sqlite:
    image: juliushaertl/nextcloud-dev
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL:
      NEXTCLOUD_AUTOINSTALL_APPS:
    volumes:
      - '${NEXTCLOUD_SOURCE}:/var/www/html'
      - nc-data-sqlite:/var/www/html/data
      - nc-config-sqlite:/var/www/html/config
    ports:
      - 8010:80

  nc-server-mysql:
    image: juliushaertl/nextcloud-dev
    environment:
      SQL: 'mysql'
      NEXTCLOUD_AUTOINSTALL:
      NEXTCLOUD_AUTOINSTALL_APPS:
    volumes:
      - '${NEXTCLOUD_SOURCE}:/var/www/html'
      - nc-data-mysql:/var/www/html/data
      - nc-config-mysql:/var/www/html/config
    ports:
      - 8011:80
    depends_on:
      - nc-database-mysql

  nc-server-postgres:
    image: juliushaertl/nextcloud-dev
    environment:
      SQL: 'pgsql'
      NEXTCLOUD_AUTOINSTALL:
      NEXTCLOUD_AUTOINSTALL_APPS:
    volumes:
      - '${NEXTCLOUD_SOURCE}:/var/www/html'
      - nc-data-postgres:/var/www/html/data
      - nc-config-postgres:/var/www/html/config
    ports:
      - 8012:80
    depends_on:
      - nc-database-postgres

  nc-database-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'jah1Yohfureeg8shoosee7ie'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'

  nc-database-postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: 'nextcloud'
      POSTGRES_PASSWORD: 'nextcloud'
      POSTGRES_DB: 'nextcloud'

volumes:
  nc-data-sqlite:
  nc-data-mysql:
  nc-data-postgres:
  nc-config-sqlite:
  nc-config-mysql:
  nc-config-postgres:
  nc-db-postgres:


